export interface Platform {
  path: string
  label: string
  icon: string
  screens: string[]
}

export const PLATFORMS: Platform[] = [
  {
    path: 'driver',
    label: 'Driver',
    icon: '🚗',
    screens: [
      'Authentication (Splash, Login, Signup, OTP, Biometric Setup)',
      'Onboarding & Profile Setup',
      'Home Dashboard',
      'Mobility Score (Vehicle Intelligence Index)',
      'Driving Reports (Weekly/Monthly)',
      'Vehicle Details & Digital Twin View',
      'Vehicle Health Breakdown',
      'Service History Timeline',
      'Predictive Maintenance Alerts',
      'Driving Analytics & Risk Exposure',
      'Trip History & Trip Summary',
      'Fuel Efficiency & Carbon Tracker',
      'Insurance Overview & Premium Calculator',
      'Claims Upload & AI Damage Assessment',
      'Claim Status Tracker',
      'Nearby Service Centers & Booking',
      'Technician Profile View',
      'Live Repair Tracking',
      'Parking Map & Booking',
      'EV Charging Booking & Usage Analytics',
      'Emergency & Accident Detection',
      'Roadside Assistance',
      'Resale Value Estimator',
      'Loan & EMI Calculator',
      'Marketplace',
      'Settings & Privacy Controls',
    ],
  },
  {
    path: 'insurance',
    label: 'Insurance',
    icon: '🛡️',
    screens: [
      'Insurance Admin Login',
      'Portfolio Overview Dashboard',
      'Real-Time Risk Monitor',
      'Driver Risk Profile View',
      'Dynamic Premium Adjustment Panel',
      'Claims Management Dashboard',
      'AI Fraud Detection Graph View',
      'Risk Heatmaps',
      'Policy Management',
      'Predictive Loss Forecasting',
      'Model Performance Monitoring',
      'Compliance Reporting',
      'API Integration Settings',
    ],
  },
  {
    path: 'dealer',
    label: 'Dealer',
    icon: '🏪',
    screens: [
      'Dealer Login & Dashboard',
      'Inventory Management',
      'Add/Edit Vehicle',
      'Digital Twin Inventory View',
      'Dynamic Pricing Engine',
      'Demand Forecast Dashboard',
      'Trade-In Valuation Tool',
      'Lead Management',
      'Customer Profile View',
      'Sales Funnel',
      'Sales Analytics',
      'Commission Management',
      'Finance Integration Panel',
      'Market Trend Insights',
    ],
  },
  {
    path: 'sales',
    label: 'Sales',
    icon: '📊',
    screens: [
      'Sales Dashboard',
      'Lead Assignment & Scoring',
      'Customer Interaction Logs',
      'Performance Metrics',
      'Commission Tracker',
      'AI Sales Suggestions',
      'Follow-Up Scheduler',
      'Target Achievement Tracker',
    ],
  },
  {
    path: 'technician',
    label: 'Technician',
    icon: '🔧',
    screens: [
      'Technician Login',
      'Job Queue Dashboard',
      'Vehicle Diagnostic Digital Twin',
      'AI Fault Detection',
      'Repair Recommendations',
      'Parts Prediction Engine',
      'Repair Workflow Tracker',
      'AR Assistance View',
      'Repair Time Estimator',
      'Technician Performance Score',
      'Earnings Summary',
    ],
  },
  {
    path: 'property',
    label: 'Property',
    icon: '🏢',
    screens: [
      'Property Admin Login',
      'Property Dashboard',
      'Parking Utilization Heatmap',
      'Slot Management',
      'Dynamic Pricing Engine',
      'EV Charging Control Panel',
      'Load Balancing Monitor',
      'Revenue Analytics Dashboard',
      'Peak Traffic Prediction',
      'Access Control Management',
      'Carbon Impact Dashboard',
    ],
  },
  {
    path: 'government',
    label: 'Government',
    icon: '🏛️',
    screens: [
      'Regulator Login',
      'National Vehicle Overview',
      'Compliance Monitoring Dashboard',
      'Emission Monitoring Panel',
      'Traffic Density Heatmap',
      'Accident Cluster Prediction',
      'Risk Zone Analytics',
      'Policy Simulation Engine',
      'Recall Monitoring',
      'Fraud Pattern Analytics',
      'Regional Reports',
      'Export & Reporting Tools',
    ],
  },
  {
    path: 'ai-admin',
    label: 'AI Admin',
    icon: '⚙️',
    screens: [
      'Super Admin Dashboard',
      'User & Role Management',
      'AI Model Monitoring',
      'Model Accuracy Dashboard',
      'Federated Learning Monitor',
      'Data Flow Visualization',
      'API Gateway Monitor',
      'System Health Dashboard',
      'Incident Management',
      'Audit Logs',
      'Security Control Center',
      'Billing & Subscription Management',
    ],
  },
  {
    path: 'analytics',
    label: 'Analytics',
    icon: '📈',
    screens: [
      'Global Performance Dashboard',
      'Mobility Score Distribution',
      'Vehicle Health Trends',
      'Insurance Risk Trends',
      'Dealer Sales Trends',
      'Technician Performance Trends',
      'Parking Revenue Trends',
      'Emission Analytics',
      'Predictive Forecast Charts',
      'AI Model Comparison Dashboard',
    ],
  },
  {
    path: 'ai-assistant',
    label: 'AI Assistant',
    icon: '🤖',
    screens: [
      'AI Chat Interface',
      'Voice Assistant Screen',
      'Predictive Suggestions Panel',
      'Context-Aware Action Suggestions',
      'AI Explanation Screen (Why This Score?)',
    ],
  },
  {
    path: 'fleet',
    label: 'Fleet',
    icon: '🚛',
    screens: [
      'Fleet Dashboard',
      'Vehicles',
      'Live Tracking',
      'Drivers & Assignments',
      'Maintenance & Service',
      'Reports & Analytics',
    ],
  },
]
